using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ProyectoWeb.Shared.DTOs
{
    public class PaisesDTO
    {
        public List<string> Paises { get; set; } = new List<string>{"Afganistán",
                                                                    "Albania",
                                                                    "Alemania",
                                                                    "Andorra",
                                                                    "Angola",
                                                                    "Antigua y Barbuda",
                                                                    "Arabia Saudita",
                                                                    "Argelia",
                                                                    "Argentina",
                                                                    "Armenia",
                                                                    "Australia",
                                                                    "Austria",
                                                                    "Azerbaiyán",
                                                                    "Bahamas",
                                                                    "Bahrein",
                                                                    "Bangladés",
                                                                    "Barbados",
                                                                    "Bélgica",
                                                                    "Belice",
                                                                    "Benín",
                                                                    "Bielorrusia",
                                                                    "Birmania",
                                                                    "Bolivia",
                                                                    "Bosnia y Herzegovina",
                                                                    "Botsuana",
                                                                    "Brasil",
                                                                    "Brunéi",
                                                                    "Bulgaria",
                                                                    "Burkina Faso",
                                                                    "Burundi",
                                                                    "Cabo Verde",
                                                                    "Camboya",
                                                                    "Camerún",
                                                                    "Canadá",
                                                                    "Chad",
                                                                    "Chequia",
                                                                    "Chile",
                                                                    "China",
                                                                    "Chipre",
                                                                    "Colombia",
                                                                    "Comoras",
                                                                    "Congo",
                                                                    "Congo, República Democrática del",
                                                                    "Costa Rica",
                                                                    "Croacia",
                                                                    "Cuba",
                                                                    "Dinamarca",
                                                                    "Dominica",
                                                                    "Dominicana, República",
                                                                    "Ecuador",
                                                                    "Egipto",
                                                                    "El Salvador",
                                                                    "Emiratos Árabes Unidos",
                                                                    "Eslovenia",
                                                                    "España",
                                                                    "Estonia",
                                                                    "Eswatini",
                                                                    "Etiopía",
                                                                    "Filipinas",
                                                                    "Finlandia",
                                                                    "Francia",
                                                                    "Gabón",
                                                                    "Gambia",
                                                                    "Georgia",
                                                                    "Ghana",
                                                                    "Granada",
                                                                    "Grecia",
                                                                    "Guatemala",
                                                                    "Guinea",
                                                                    "Guinea Ecuatorial",
                                                                    "Guinea-Bisau",
                                                                    "Haití",
                                                                    "Honduras",
                                                                    "Hungría",
                                                                    "India",
                                                                    "Indonesia",
                                                                    "Irán",
                                                                    "Iraq",
                                                                    "Irlanda",
                                                                    "Islandia",
                                                                    "Islas Marshall",
                                                                    "Islas Salomón",
                                                                    "Islas Seychelles",
                                                                    "Italia",
                                                                    "Jamaica",
                                                                    "Japón",
                                                                    "Jordania",
                                                                    "Kazajistán",
                                                                    "Kenia",
                                                                    "Kirguistán",
                                                                    "Kiribati",
                                                                    "Kuwait",
                                                                    "Laos",
                                                                    "Letonia",
                                                                    "Líbano",
                                                                    "Liberia",
                                                                    "Libia",
                                                                    "Liechtenstein",
                                                                    "Lituania",
                                                                    "Luxemburgo",
                                                                    "Madagascar",
                                                                    "Malasia",
                                                                    "Malaui",
                                                                    "Maldivas",
                                                                    "Malta",
                                                                    "Marruecos",
                                                                    "Mauricio",
                                                                    "Mauritania",
                                                                    "México",
                                                                    "Micronesia",
                                                                    "Mónaco",
                                                                    "Mongolia",
                                                                    "Mozambique",
                                                                    "Namibia",
                                                                    "Nauru",
                                                                    "Nepal",
                                                                    "Nicaragua",
                                                                    "Níger",
                                                                    "Nigeria",
                                                                    "Noruega",
                                                                    "Nueva Zelanda",
                                                                    "Omán",
                                                                    "Países Bajos",
                                                                    "Pakistán",
                                                                    "Palaos",
                                                                    "Panamá",
                                                                    "Paraguay",
                                                                    "Perú",
                                                                    "Polonia",
                                                                    "Portugal",
                                                                    "Reino Unido",
                                                                    "República Centroafricana",
                                                                    "República Checa",
                                                                    "República del Congo",
                                                                    "República Dominicana",
                                                                    "Rumanía",
                                                                    "Rusia",
                                                                    "Rwanda",
                                                                    "San Cristóbal y Nieves",
                                                                    "San Marino",
                                                                    "San Vicente y las Granadinas",
                                                                    "Santa Lucía",
                                                                    "Santo Tomé y Príncipe",
                                                                    "Arabia Saudita",
                                                                    "Senegal",
                                                                    "Serbia",
                                                                    "Seychelles",
                                                                    "Sierra Leona",
                                                                    "Singapur",
                                                                    "Eslovenia",
                                                                    "Somalia",
                                                                    "Sudáfrica",
                                                                    "Sudán",
                                                                    "Sudán del Sur",
                                                                    "Suecia",
                                                                    "Suiza",
                                                                    "Siria",
                                                                    "Tailandia",
                                                                    "Tanzania",
                                                                    "Tayikistán",
                                                                    "Timor Oriental",
                                                                    "Togo",
                                                                    "Tonga",
                                                                    "Trinidad y Tobago",
                                                                    "Túnez",
                                                                    "Turkmenistán",
                                                                    "Turquía",
                                                                    "Tuvalu",
                                                                    "Uganda",
                                                                    "Ucrania",
                                                                    "Emiratos Árabes Unidos",
                                                                    "Reino Unido",
                                                                    "Estados Unidos",
                                                                    "Uruguay",
                                                                    "Uzbekistán",
                                                                    "Vanuatu",
                                                                    "Vaticano",
                                                                    "Venezuela",
                                                                    "Vietnam",
                                                                    "Yemen",
                                                                    "Zambia",
                                                                    "Zimbabue"
                                                                    };
    }
}
